export const GET_PRODUCTS = "GET_PRODUCTS";
export const SHOW_ERROR = "SHOW_ERROR";
export const CLEAR_MESSAGE_ERROR = "CLEAR_MESSAGE_ERROR";
export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const USER_LOGIN = "USER_LOGIN";
